---
kind: pipeline
type: docker
name: terra

steps:
  - name: plan-insights
    pull: if-not-exists
    image: hashicorp/terraform:0.14.10
    environment:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    commands:
      - apk add -U make openssh-client jq zip
      - mkdir ~/.ssh && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519 && chmod 0600 ~/.ssh/id_ed25519
      - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - make -C .terra/insights init
      - make -C .terra/insights validate

  - name: plan-superset
    pull: if-not-exists
    image: hashicorp/terraform:0.14.10
    environment:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    commands:
      - apk add -U make openssh-client jq zip
      - mkdir ~/.ssh && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519 && chmod 0600 ~/.ssh/id_ed25519
      - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - make -C .terra/superset init
      - make -C .terra/superset validate
---
kind: pipeline
type: docker
name: backend

steps:
  - name: unit-test
    pull: if-not-exists
    image: python:3.9
    environment:
      SUPERSET_SECRET_KEY: asd123
    commands:
      - mkdir ~/.ssh && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519 && chmod 0600 ~/.ssh/id_ed25519
      - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - apt-get update && apt-get install libsasl2-dev
      - pip install -r requirements/testing.txt
      - cp -R bi_superset/ superset/bi_superset/
      - cp bi_superset/superset_config.py superset/superset_config.py
      - cp bi_superset/bi_cli/bi_cli.py superset/cli/bi_cli.py
      - cp -R zf_integration/ superset/zf_integration/
      - cp zf_utils/jwt.py superset/utils/jwt.py
      - pip install coverage
      - pip freeze
      - pytest -v ./tests/unit_tests/ --cov-report xml:coverage.xml

  - name: coverage-push
    pull: if-not-exists
    image: python:3.8
    commands:
      - curl -X POST -H "Content-Type:text/xml" -d @coverage.xml "devportal.zerofox.com/api/code-coverage/report?entity=system:default/superset&coverageType=cobertura"
    when:
      branch:
        - master
      event:
        - push

---
kind: pipeline
type: docker
name: frontend

steps:
  - name: integration-test
    pull: if-not-exists
    image: node:14
    environment:
      SUPERSET_SECRET_KEY: asd123
    commands:
      - mkdir ~/.ssh && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519 && chmod 0600 ~/.ssh/id_ed25519
      - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - cp -R bi_superset/ superset/bi_superset/
      - cp bi_superset/superset_config.py superset/superset_config.py
      - cp bi_superset/bi_cli/bi_cli.py superset/cli/bi_cli.py
      - cp -R zf_integration/ superset/zf_integration/
      - cp zf_utils/jwt.py superset/utils/jwt.py
      - cd superset-frontend && npm ci
      - npm run build
      - npm run test