---
kind: pipeline
type: docker
name: terra

steps:
  - name: plan
    pull: if-not-exists
    image: hashicorp/terraform:0.11.15
    environment:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    commands:
      - apk add -U make openssh-client jq zip
      - mkdir ~/.ssh && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519 && chmod 0600 ~/.ssh/id_ed25519
      - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - make -C .terra/ init
      - make -C .terra/ validate