site_name: superset documentation
repo_url: https://github.com/riskive/superset-external/
nav:
    - Home: README.md
    - Release+Deploy: RELEASE+DEPLOY.md
    - Testing: TESTING.md
    - New Plugin: add-new-plugin.md
    - Contributing: CONTRIBUTING.md
    - Upgrading Superset: UPGRADING_SUPERSET.md
plugins:
    - techdocs-core
