version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./dev/secrets/.env

  superset:
    image: superset:latest
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/service-acct.json
    volumes:
      - ./superset:/etc/superset
      - ./dev/secrets/:/secrets/
      - ./config/superset_config_local.py:/superset_config.py
      - ./config/custom_bi_security_manager.py:/custom_bi_security_manager.py
      - ./config/bi_security_manager/:/bi_security_manager/
    env_file:
      - ./dev/secrets/.env

  worker:
    image: superset:latest
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/service-acct.json
    volumes:
      - ./superset:/etc/superset
      - ./dev/secrets/:/secrets/
      - ./config/superset_config_local.py:/superset_config.py
      - ./config/custom_bi_security_manager.py:/custom_bi_security_manager.py
      - ./config/bi_security_manager/:/bi_security_manager/
    env_file:
      - ./dev/secrets/.env

    command: "celery --app=superset.tasks.celery_app:app worker"

  flower:
    image: superset:latest
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "5555:5555"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/service-acct.json
    volumes:
      - ./superset:/etc/superset
      - ./dev/secrets/:/secrets/
      - ./config/superset_config_local.py:/superset_config.py
      - ./config/custom_bi_security_manager.py:/custom_bi_security_manager.py
      - ./config/bi_security_manager/:/bi_security_manager/
    env_file:
      - ./dev/secrets/.env

    command: "celery --app=superset.tasks.celery_app:app flower"

  beat:
    image: superset:latest
    command: "celery --app=superset.tasks.celery_app:app beat"
    restart: unless-stopped
    env_file:
      - ./dev/secrets/.env

    volumes:
      - ./superset:/etc/superset
      - ./dev/secrets/:/secrets/
      - ./config/superset_config_local.py:/superset_config.py
      - ./config/custom_bi_security_manager.py:/custom_bi_security_manager.py
      - ./config/bi_security_manager/:/bi_security_manager/

    healthcheck:
      disable: true

volumes:
  postgres:
  redis:
